### PR TITLE
Feat: Added Wishlist html

### PR DESCRIPTION
**Pull request by rahulcs754**
- added wishlist html code

image

### CODE REVIEW

**Review by SimranjitKaurMaan — COMMENTED** [review]
badge of 10 in the header looks very far.

**Review by SimranjitKaurMaan — APPROVED** [review]
Can be merged. Only 1 small suggestion.

**Review by tanishq20 — APPROVED** [review]
Code looks good. Only small suggestion is to please use prettier to arrange the code. Too many extra spaces are there.

**Comment by rahulcs754** [comment]
done with prettier

**Comment by rahulcs754** [comment]
image

Hi, Simranjit my icon is not showing why you think that is far away. 
now i am set my icon

**Pull request merged**
